### ISSUE TITLE
things perception is not working

### ISSUE THREAD

**Issue by cehberlin** [agentcontest/massim_2019#1]
Hi,
I am testing the current source version and I am trying to adapt to the new protocol. During these tests, it seems to me that the things part in the perception is not working correctly. The attached screenshot shows the raw perception of agent A1 in the debugger.

![mapc19_things](https://user-images.githubusercontent.com/327393/57681996-205dbd00-7631-11e9-9135-0f5069db54e0.png)

Here, I moved the agent to the right from its initial position and it seemed like the perception range is about 4 blocks. In consequence, I would expect perception about agents B1 and B9 as well as ?dispenser? b2.

**Comment by t-ah** [comment]
Thanks.
b2 (dispenser) should be perceivable now. Still trying to figure out where B1 is, though.

**Comment by t-ah** [comment]
I believe it's fixed now.
