### ISSUE TITLE
[BUG] Internal Grid Location For Things Are Incorrect When Updated

### ISSUE THREAD

**Issue by MikeVezina** [agentcontest/massim_2019#5]
Not sure if anyone else is having this issue, but I noticed that the server was sending a FAILED action response whenever I submitted a task (even though the required blocks were attached in the correct locations and the agent was on a goal cell). After looking into this further, it looks like the grid used internally by the server is not updated correctly when moving an entity. This issue is not shown on the monitor (all locations are shown correctly). This issue only persists when the server verifies agent actions such as submit or move.

### Code Responsible for Issue
The lines of code that correspond to this issue can be found on Lines 84 and 85 in the file: https://github.com/agentcontest/massim_2019/blob/master/server/src/main/java/massim/game/environment/Grid.java

Lines 84 and 85 are as follows:
```
insertThing(thing);
thing.setPosition(newPos);
```

The issue is that `insertThing(thing)` updates the thing location on the grid using `thing.getPosition()`, but the new position of the thing only gets set after the call to insertThing. This results in the grid not recognizing some entities. 

The following code is the definition for insertThing. As we can see, it updates the grid to contain the thing on it's non-updated position.
```
private boolean insertThing(Positionable thing) {
        if (outOfBounds(thing.getPosition())) return false;
        getThings(thing.getPosition()).add(thing); // Offending line of code, uses old position of thing
        return true;
    }
```

### Example
To give an example of this issue, let's say we have an agent on (3,5) that has completed all task requirements for task T and would like to submit the task to goal cell (5,5). The agent does the following:
1. move(e)
2. move(e)
3. submit(T)

The server responds with FAILED (agent not on goal cell), although on the monitor the agent is clearly on the goal cell. If we query the Grid object for the agent entity (`getThings(new Position(5,5))`) we get an empty set, but the set should contain the agent entity.

### Corresponding Fix
The corresponding fix is an easy one. Swap lines 84 and 85 of Grid.java so that the thing position gets updated before insertThing(thing) is called. I've verified this locally, but I welcome other people to reproduce this issue and verify this fix before it is pushed into master. If appropriate, I can submit a pull request with the fix.

Code Fix (this is actually done correctly in the method moveWithoutAttachments() on line 94 in Grid.java):
```
thing.setPosition(newPos);
insertThing(thing);
```

Please feel free to provide any comments or suggestions in case I may have missed something!

Thanks,
Michael

**Comment by t-ah** [comment]
Thank you very much! :)
