### ISSUE TITLE
Agent-Invoked Clear Markers Not Showing Up In Perceptions

### ISSUE THREAD

**Issue by MikeVezina** [agentcontest/massim_2019#6]
Not sure if this is a bug or intended behaviour, but based on my understanding of the clear action documentation this seems like this might be a bug.

This issue occurs when agents call the clear(...) action. No marker is perceived by any of the agents. **Simulation generated clear events do not encounter this issue.**

For example:
agent **A1** runs **clear(0,1)** successfully.
agent **A1** and **A2** (who are both in the vision range of the clear marker) do **not** perceive thing(_, _, marker, _)

My understanding of the clear action documentation is that all agents within the vision range of the marker generated by A1 should perceive it.  If my understanding is incorrect, please let me know. This issue persists even if the agent calls clear(0,1) successfully three times in a row to invoke the clear event. No perceptions are generated for the markers or agent clear event at all.

After looking into the Simulator code, this seems to be the sequence that causes this issue (in GameState.java):
1. **handleClearAction** correctly adds markers to the grid when the agent sends clear(0, 1).

2. Then, on the next simulation step: 
3. **prepareStep** deletes the markers (**grid.deleteMarkers()**)
4. **prepareStep** then only creates marker thing perceptions for clearEvents (which only contains clear events randomly created by the server).

(If my understanding of the clear action is correct and that the agents should perceive the markers, then I think that all agent-generated markers should also be added to the list of grid markers).

Any clarification would be appreciated. Thank you!

**Comment by t-ah** [comment]
That is completely right. Thank you very much! ..again :)
